### ISSUE TITLE
Clear cache button generates 500 error

### ISSUE THREAD

**Issue by joeke** [modx-pro/frontendmanager#11]
When clicking the Clear cache button, an Ajax request to /manager/?a=system/refresh_site is sent, but this generates the following 500 error:

2017/01/26 18:57:45 [error] 7488#0: *4594 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file 'system/refresh_site.tpl' <-- 
  thrown in /my/local/path/to/modx/core/model/smarty/sysplugins/smarty_internal_template.php on line 219" while reading response header from upstream ****

Is this a known issue, or is this an issue on my local setup?

**Comment by but1head** [comment]
I think this is a problem because of the local installation. Which version MODx?

**Comment by joeke** [comment]
MODX version: 2.5.2
PHP: 7.0.14
Mysql 5.5.53 MariaDB

**Comment by joeke** [comment]
I think I found the issue: I'm using a custom manager template which doesn't have the system/refresh_site.tpl file. When I copy the file from the default theme folder to my custom theme folder the issue is fixed. So it looks more like a MODX core issue, as I believe the manager templating system always has a fallback to the default theme when a file is not present in your manager theme. Maybe the fallback system does not work for this specific file or something... anyway it's not an issue with frontendmanager, so I'm closing this issue. Thanks for your quick response and help Nikita!
